### ISSUE TITLE
Mirones sites missing charts

### ISSUE THREAD

**Issue by agrignard** [agrignard/PROXYKIT#2]
Why don't we have the chart for Mirones? 
<img width="1045" alt="Screenshot 2021-05-06 at 14 35 22" src="https://user-images.githubusercontent.com/3928502/117299043-5cbb0100-ae78-11eb-92e5-a1cc2f4e344d.png">

<img width="1792" alt="Screenshot 2021-05-06 at 14 31 32" src="https://user-images.githubusercontent.com/3928502/117299023-575db680-ae78-11eb-8c2e-67d582efb951.png">

**Comment by ptaillandier** [comment]
Are you sure, Could you test again, because I have them:
<img width="454" alt="mirones" src="https://user-images.githubusercontent.com/1506077/117425092-ac6afc80-af4c-11eb-8285-939db4c30af1.PNG">

**Comment by agrignard** [comment]
Ok sorry it's working now. I don't know what happened
