### ISSUE TITLE
Demographic Data

### ISSUE THREAD

**Issue by agrignard** [agrignard/PROXYKIT#3]
@ptaillandier can you point me to the right file that needs to be completed by LIMA for the demographic data?

As discussed last time I think we need this kind o finformation but it would be great if you can tell me directly the file that are concern so I can then point it to the IDB/Lima team

- **demographic** (Proportion of households only composed of old people (without children): 0.3
Mean number of children: 1.8
Standard deviation of the number of children: 0.5
Max number of children: 5
Probability to have a grandfather at home: 0.1
Probability to have a grandmother at home: 0.1
Retirement age: 65
Mean number of friends: 3.0
Standard deviation of the number of friends: 3.0
Mean number of classmates: 10.0 
Standard deviation of the number of classmates:5.0
Mean number of colleagues: 5.0
Standard deviation of the number of colleagues: 3.0
Unemployed rate: 0.1
Rate of people working at home: 0.1)

- **Activity Data** (Non working days: Saturday and sunday
Work hours : [7,10] – [15-18]
School hours: [7,9] – [15-18]
Lunch hours: [11-13]
Max duration for lunch: 2h
Max duration for default activities: 3h
Min age for evening activity: 13 
Mean number of friends sharing the activity: 3.0
Average number of friends sharing the activity: 2.0
Max number of activities for non working day: 4
Max number activities per day for old people: 3
Max number activities per day for unemployed people: 3
Rate of people having evening activity: 0.4
Rate of people having lunch outside workplace: 0.5
Rate of people having lunch at home: 0.5
Probability of doing activity outside: 0.3
Rate of people working outside: 0.7
Distance for considering neighbors: 100

**Comment by ptaillandier** [comment]
The information requires:

### Population
We have two ways of defining the population: ad'hoc generator or Gen*

**If we use the ad'hoc generator:**
**population parameter.csv**
- male_ratio : the probability to be a male (1 - male_ratio gives the probability to be a female). Default is 21/41
- proba_active_family : the probability to create a two or more persons household (1 - proba_active_family being the probability to create a lone individual household). Default is 0.95
- number_children_mean : the mean (expected value) number of children per household. Default is 2.0
- number_children_std : the standard deviation (variance) to determine the number of children per household. Default is 0.5
- number_children_max : the maximum number of children per household. Default is 3
- proba_grandfather : the probability to include the grandfather in the household. Default is 0.2
- proba_grandmother : the probability to include the grandmother in the household. Default is 0.3
- retirement_age : the age threshold for retirement. Default is 55
- max_age : the maximum age an agent can have at initialization. Default is 100
- nb_friends_mean : the mean (expected value of a Gaussian) number of friends per individual agent. Default is 5.0
- nb_friends_std : the standard deviation (variance of a Gaussian) to determine the number of friends per individual. Default is 3.0
- nb_classmates_mean : mean number of classmates with which an Individual will have close contact. Default is 10.0
- nb_classmates_std : stand deviation of the number of classmates with which an Individual will have close contact. Default is 5.0
- nb_work_colleagues_mean mean number of work colleagures with which an Individual will have close contact. Default is 5.0
- nb_work_colleagues_std : stand deviation of the number of work colleagures with which an Individual will have close contact.  Default is 3.0
- proba_work_at_home : the probability to do remote work. Default is 0.05
- proba_unemployed_M : the probability for a male individual agent to be unemployed. Default is 0.03
- proba_unemployed_F : the probability for a female individual agent to be unemployed. Default is 0.03

**if we use Gen*:**
- the number of people living in the area per age category and per gender and information about their occupation
- nb_friends_mean : the mean (expected value of a Gaussian) number of friends per individual agent. Default is 5.0
- nb_friends_std : the standard deviation (variance of a Gaussian) to determine the number of friends per individual. Default is 3.0
- nb_classmates_mean : mean number of classmates with which an Individual will have close contact. Default is 10.0
- nb_classmates_std : stand deviation of the number of classmates with which an Individual will have close contact. Default is 5.0
- nb_work_colleagues_mean mean number of work colleagures with which an Individual will have close contact. Default is 5.0
- nb_work_colleagues_std : stand deviation of the number of work colleagures with which an Individual will have close contact. Default is 3.0
- proba_work_at_home : the probability to do remote work. Default is 0.05

**In addition to that, it will be nice to know:**
- the number of people living outside the considered area, but working inside the area
- the number of people living outside the considered area, but doing activity inside the area (ideally, the number per activity type).

### Agenda

**Agenda parameter.csv**
- non_working_days : List of non working days (1: Monday, 7: Sunday). Default is [7]
- work_hours_begin_min : the minimal value for the beginning working hour (between 0 and 23). Default is 6
- work_hours_begin_max : the maximal value for the beginning working hour (between 0 and 23). Default is 10
- work_hours_end_min : the minimal value for the ending working hour (between 0 and 23). Default is 15
- work_hours_end_max : the maximal value for the ending working hour (between 0 and 23). Default is 18
- school_hours_begin_min : the minimal value for the beginning school hour (between 0 and 23). Default is 7
- school_hours_begin_max : the maximal value for the beginning school hour (between 0 and 23). Default is 9
- school_hours_end_min : the minimal value for the ending school hour (between 0 and 23). Default is 15
- school_hours_end_max : the maximal value for the ending school hour (between 0 and 23). Default is 18
- first_act_hour_non_working_min : For non working day (or people who are not working), minimal hour for the beginning of the first activity (between 0 and 23). Default is 7
- first_act_hour_non_working_min : For non working day (or people who are not working), maximal hour for the beginning of the first activity (between 0 and 23). Default is 10
- lunch_hours_min : the minimal value for the beginning of the lunch time (between 0 and 23). Default is 11
- lunch_hours_max : the maximal value for the beginning of the lunch time (between 0 and 23). Default is 13
- max_duration_lunch : the maximal duration (in hours) of the lunch time. Default is 2
- max_duration_default : the maximal duration (in hours) of other activities. Default is 3
- min_age_for_evening_act : the minimal age of individual to have an activity after school. Default is 13
- nb_activity_fellows_mean : the mean number of fellows per activity. Default is 3.0
- nb_activity_fellows_std : the standard deviation of the number of fellows per activity. Default is 2.0
- max_num_activity_for_non_working_day : the maximal number of activities for non working day. Default is 4
- max_num_activity_for_unemployed : the maximal number of activities per day for unemployed individual. Default is 3
- max_num_activity_for_old_people : the maximal number of activities per day for retired individual. Default is 3
- proba_activity_evening : the probability for people to have an activity after work. Default is 0.7
- proba_lunch_outside_workplace : the probability to have lunch outside the working place (home or restaurant). Default is 0.5
- proba_lunch_at_home : if lunch taken outside the working place, the probability of having lunch at home. Default is 0.5
- proba_work_outside : the probabilty for an individual to work outside the considered area. Default is 0.0
- proba_go_outside : the probabilty for an individual to do an activity outside the considered area. Default is 0.0
- building_neighbors_dist : the maximal distance (in meter) of the considered neigbhorhood for the “visit to neighbors” activity. Default is 500.0
