### ISSUE TITLE
Different scenario Methodology

### ISSUE THREAD

**Issue by agrignard** [agrignard/PROXYKIT#4]
Now the model works well in its generic form now.

@ptaillandier What would be the next steps to be able to present the tool and "use" it? I was thinking that we coudl specify different scenarios in a first step? 

I guess they are already different project that has been using this kind of approach.

What would be the good ay to do it with LIMA? Should we define a model where we have different experiment with different parameters? And then giving a kind of explanation of each scenario?

Is there some already pre cooked scenario in Comokit?

**Comment by ptaillandier** [comment]
Indeed, the next step is now to define the scenarios. In particular, for each scenario, we should define :
- the area involved, the type of intervention implemented, the output indicators.

This will allow us to see if we can directly implement the experiments or if we need to develop new things (interventions, indicators, etc.).

As far as COMOKIT built-in scenarios, there are some on containment, testing/isolation, masks. We're working on vaccines, but I don't know when that will be operational yet (Kevin is working on it, but he just had a baby a week ago, so it's going to be a little slow).

So the first thing is to agree on the types of interventions to be tested. Afterwards, we can do several experiments by varying the parameters.

**Comment by agrignard** [comment]
Do you have a  list of stuff that can be tested?

Ideally I would say for the classic generic ones
Mask
Social Distance
Density
Quratine (of a certain percentage of the population)

And then we migth need some more specific intervention here like
Closing some shops or closing some part of the district etc
